### ISSUE TITLE
takeEvery misses actions if the referenced saga forks/spawns

### ISSUE THREAD

**Issue by avaragado** [yelouafi/redux-saga#544] opened 2016-09-14 11:49 UTC
I've encountered a problem with takeEvery, in which some actions are being missed. This is with redux-saga 0.11.1 and redux 3.5.2.

Here's some code that exhibits the problem:

``` js
import { takeEvery } from 'redux-saga';
import { fork, put, take, call, spawn } from 'redux-saga/effects';

function * test () {
    const hello = (id) => {
        console.log('HELLO', id);
    };

    function * respond (action) {
        yield fork(hello, action.id);     // only message shown is 'HELLO 1'
        // yield spawn(hello, action.id); // only message shown is 'HELLO 1'
        // yield call(hello, action.id);  // both 'HELLO 1' and 'HELLO 2' appear
    }

    function * watch () {
        yield takeEvery('ABC', respond);
    }

    yield spawn(watch);

    yield [
        put({ type: 'ABC', id: 1 }),
        put({ type: 'ABC', id: 2 }),
    ];
}

export default function * root () {
    yield [
        fork(test),
    ];
}
```

I would expect both ABC actions to result in a HELLO message however the `respond` saga invokes the `hello` function. Instead, if `fork` or `spawn` is used, only the first action is recognised.

I don't _think_ I'm doing anything fundamentally daft here...

Thanks for a great library!

**Comment by yelouafi** [comment] 2016-10-02 18:10
Could you try with the new release? I think the issue is resolved

**Comment by yelouafi** [comment] 2016-11-30 20:07
closing this. will reopen if the issue isn't resolved yet

**Closed by yelouafi** 2016-11-30 20:07 UTC
