### ISSUE TITLE
Put actions as one batch

### ISSUE THREAD

**Issue by satispunk** [yelouafi/redux-saga#15] opened 2015-12-23 22:24 UTC
Is this possible to put several actions in batch else each put leads to re-render of components?

put([...actions]) or put(action1, action2, action3, ...) would be great.

**Comment by yelouafi** [comment] 2015-12-23 22:51
I think this is more related to React/React-redux than redux-saga itself.

Related to 'physical rendering' (patching the real DOM) I think there is no worry here because React will batch (or debounce) multiple renders in the next animation frame.

Now for the 'logical render' (calling the render method of components) I can't say. It depends on how React-redux is implemented. Maybe @gaearon can tell us more about this.

**Comment by gaearon** [comment] 2015-12-23 23:42
React won't batch renders by default but you can tell it to with ReactDOM.unstable_batchedUpdates—either manually or via https://github.com/tappleby/redux-batched-subscribe. 

In any case this is out of scope of Redux Saga.

**Comment by yelouafi** [comment] 2015-12-23 23:52
>React won't batch renders by default but you can tell it to

Didn't know that. I thought that animation frame debouncing was automatic

**Comment by gaearon** [comment] 2015-12-24 00:16
It batches updates if you're inside an event handler. So for dispatches caused by a click, for example, it will be fine. But it doesn't do that in other cases such as AJAX callbacks. There are plans to implement this for all cases but there hasn't been a dedicated effort yet.

**Comment by yelouafi** [comment] 2015-12-24 00:21
So, if we dispatch all actions inside the same (micro)-task queue, this will be fine.

**Comment by gaearon** [comment] 2015-12-24 00:57
I'm not well versed in micro tasks in JS. I'm fairly certain React explicitly wraps its event handlers with batching but I don't think it works in other cases. Regardless you can always opt into this with the package I linked to and ReactDOM.unstable_batchedUpdates().

**Comment by yelouafi** [comment] 2015-12-24 01:53
micro tasks (like used by promise.then) are executed withing the same event loop. Meaning even if the overall code triggered by the event handler dispatches multiples actions, We'll stay in the same event loop cycle, If React doesn't touch the DOM during this interval, no browser render will occur.

I mentioned them because redux-saga dispatches actions from Sagas using microtasks (using promises). If you look at [the real-example bootstrap code](https://github.com/yelouafi/redux-saga/blob/master/examples/real-world/index.js#L15-L23) you'll see I m delaying the render until the next animation frame. Otherwise, the Render will occur synchronously, and the Sagas may miss some startup events (especially the Router related events) because `take` effect will run only on a future microtask. 

using requestAnimationFrame ensures Sagas are ready to take actions before the UI starts to fire anything. requestAnimationFrame will always be scheduled in a new macro-task, i.e. after all scheduled microtasks terminate

**Comment by satispunk** [comment] 2015-12-24 09:55
Interesting! Didn't know about React handlers. I have noticed that there is a difference while dispatching actions in component handlers and promise callbacks

So what do you suggest guys if I have similar code? I would like that last 3 put call will no call render each time

```javascript
yield put(request())
        try {
            const state = getState()
            const login = state.LOGIN_VIEW.get('login')
            const password = state.LOGIN_VIEW.get('password')
            const data = {login, password}
            invalidate(data)

            const response = yield call(post, loginUrl(), data)
            yield put(success())
            yield put(user(response))
            yield put(navigate(V.USER_INFO_VIEW))
        }
        catch (error) {
            console.error(error)
            yield put(failure(error))
        }
```

**Comment by gaearon** [comment] 2015-12-24 12:06
I suggest you to use redux-batched-subscribe as I said above. Alternatively you can do this: https://github.com/tshelburne/redux-batched-actions

**Comment by slorber** [comment] 2015-12-24 12:14
@yelouafi take care with requestAnimationFrame

I've been using it in the past and we got problems with text inputs where the caret jumped. I know Om uses requestAnimationFrame and they used to wrap the default react inputs to avoid this problem. I don't know if it works better by default today.

**Comment by satispunk** [comment] 2015-12-24 12:18
@gaearon Thx. I will try.

**Comment by yelouafi** [comment] 2015-12-24 13:05
@slorber Didn't know that, thanks.

In the  real-world example I m using it only at the startup to delay the first Render. Until Sagas has finished with registring their take actions.

**Closed** 2015-12-30 15:04 UTC

**Comment by jimbol** [comment] 2017-05-19 14:56
Does [`all`](https://github.com/redux-saga/redux-saga/tree/master/docs/api#alleffects---parallel-effects) serve the same purpose as `batched-actions`?  I am assuming no, but perhaps you can shed light on this, @yelouafi.

**Comment by Andarist** [comment] 2017-05-19 16:25
@jimbol 

No, its doesnt serve the same purpose. You might know `yield all()` already as `yield [...arrayOfEffects]`. We've added this `all` as we prefer keeping things explicit (`all` effect) rather than implicit (yielding arrays).

`all` is by no means tied to `put`s. You can use with any other effect - useful with 2 parallel `call`s, or `fork`s etc.

Keep in mind that due to synchronous nature of redux-saga and single-threaded javascript if you `all([put(ACTION1), put(ACTION2), put(ACTION3)])` they will get dispatched to ur store one by one, probably from the left to right, but I wouldnt count on that order as it might break in the future (it shouldnt, but u know how it is... if we change internals somehow, ordering of this might be affected). This is considered to be a parallel effect and to execute effects in it *all* at once and such mental model u should apply when working with this.

**Comment by jimbol** [comment] 2017-05-19 17:02
Thought so, thanks @Andarist!

**Comment by pizza-r0b** [comment] 2019-04-24 03:40
`yield all([put(ACTION)])` doesn't seem to work.
