### ISSUE TITLE
weird error stack trace and error printing

### ISSUE THREAD

**Issue by WaiSiuKei** [yelouafi/redux-saga#287] opened 2016-04-29 05:11 UTC
Let say I throw an error in `render()` of `React` component, the console output is ok. But if i try `console.log(this.a.b.c.d.e.f)` instead, the console error message is sent by `redux-saga` to point out that the error is caused by the last saga even if that saga is well tested, and the stack trace is helpless as it just show the location of the `log()` utils func in `redux-sage` source code but not the wrong `console.log(this.a.b.c.d.e.f)`

**Comment by yelouafi** [comment] 2016-04-29 08:34
what version are you using? the v0.10.0 has some improvements on error reporting

https://cloud.githubusercontent.com/assets/5453835/14753131/30f3dd10-08cb-11e6-869e-6519cd463ff7.png

As for getting the exact location of the error (i.e. console.log) this is not possible to inside a library and requires external tooling like a babel plugin

**Comment by WaiSiuKei** [comment] 2016-04-29 13:15
I am using v0.10.0 and noted the improvement of error printing whick helps a lot to trace exceptions in sagas.

The problem I meet is that my code work like below 
```js
class Chart extends Component{
  componentDidMount(){this.doSomething()}
  doSomething(){
   let a = undefined.getFullyear()
  }
  render(){...}
}
```
But I get a error report like this
![1](https://cloud.githubusercontent.com/assets/12220022/14916354/c6476992-0e4b-11e6-86a4-8a2feed33c53.PNG)

Then I change the code like this
```js
class Chart extends Component{
  componentDidMount(){
  let a = undefined.getFullyear()
 }
 render(){...}
}
```
This time I get rignt error report
![2](https://cloud.githubusercontent.com/assets/12220022/14916907/d12b35e8-0e4e-11e6-8b05-25b3c8b05dae.PNG)

I want to know how is this wired problem caused?

**Comment by yelouafi** [comment] 2016-04-29 13:56
clicking on the arrow of the first trace will give you the raw JS trace

**Comment by WaiSiuKei** [comment] 2016-04-29 14:10
sorry for my bad screenshot, the trace of the first one will help nothing
![3](https://cloud.githubusercontent.com/assets/12220022/14918553/1abb9d4e-0e57-11e6-8f62-be91093d39c3.PNG)

**Comment by WaiSiuKei** [comment] 2016-04-29 14:58
I reproduce the bug in the [jsfiddle](https://jsfiddle.net/wakiki/uap1jskd/) by changing [https://github.com/yelouafi/redux-saga/blob/master/examples/shopping-cart/src/components/Product.js](https://github.com/yelouafi/redux-saga/blob/master/examples/shopping-cart/src/components/Product.js) to be 
```js
import React, { Component, PropTypes } from 'react'

export default class Product extends Component {
  componentDidMount(){
    this.doSomething()
  }
  doSomething(){
    let a = undefined.getFullyear()
  }
  render() {
    const { price, quantity, title, action } = this.props
    return (
      <div>
        {title} - &#36;{price} {quantity ? `x ${quantity}` : null}
        {' '}
        {action}
      </div>
    )
  }
}

Product.propTypes = {
  price: PropTypes.number,
  quantity: PropTypes.number,
  title: PropTypes.string,
  action: React.PropTypes.node
}
```

you can find the console output similar to the the attached above.

**Comment by yelouafi** [comment] 2016-04-29 14:58
From the trace it appears the error is raised in the `open` saga; while it's trying to execute some Effect. Can't really see the link with React component, unless you're trying to render from within the Saga.

**Comment by yelouafi** [comment] 2016-04-29 14:59
Ah didn't say your last message; I'll check

**Comment by yelouafi** [comment] 2016-04-29 15:24
In the fiddle, the error is thrown while the Saga is executing a `put` Effect. Seems the dispatching causing react-redux's Connect React to re-render the React Component. the Error is thrown from the Saga (because it was thrown in the same stack frame of `yield put`), However Can't understand why all React specific calls where removed from the stack trace

**Comment by WaiSiuKei** [comment] 2016-04-29 15:54
That sounds like to have something to do with the length limit of stack trace, but when I change the location of the wrong line a little, as I mention above,  this bug is gone. And one more thingis that, aftet hot replacement by webpack ,the bug will also gone.

**Comment by npbee** [comment] 2016-05-04 23:01
I think I've been experiencing this issue recently.  I've been digging into it a bit and I haven't quite figured it out but thought I'd pass along some info.  

It seems like there are two issues that may or may not be related.  First is the fact that `redux-saga` is seemingly throwing errors initially thrown by React components.  @yelouafi, like you said, I traced this to a `put` effect updating my state, which caused `react-redux` to render components that had errors.  However, one strange thing I noticed was that the behavior seems to change when using promises.  Here's a fiddle to demonstrate:  

https://jsfiddle.net/npbee/d5dt0fmw/4/

If you comment out the promise `call` at line 35, the error is thrown by React and not `redux-saga`.  

The second issue I think is what this issue was originally about.  When `redux-saga` _does_ throw, the full stack traces aren't there.  The best I could do was trace it back to this line:

https://github.com/yelouafi/redux-saga/blob/master/src/internal/proc.js#L237

```javascript
if(result instanceof Error)
    result.sagaStack = `at ${name} \n ${result.sagaStack || result.message}`
```

It seems like it's just building up a new stack from the `message` of the given error and throwing away any stack trace info that may already be there. 

Let me know if any other info would be helpful!

**Comment by brabeji** [comment] 2016-05-10 08:54
@npbee your second point is what I've debugged today, too. I think the problem is that `result.stack` (where the precious stack is) is not passed into successive log call.

https://github.com/yelouafi/redux-saga/blob/master/src/internal/proc.js#L243

```
if(result instanceof Error) {
    result.sagaStack = `at ${name} \n ${result.sagaStack || result.message}`
}
if(!task.cont) {
    log('error', `uncaught`, result.sagaStack || result.message)
}
```

**Comment by yelouafi** [comment] 2016-05-10 09:03
I think the issue comes from the `log('error', ...)` call. In the browser the call translates to `console.error` which prints the error stack at the moment of the console.error call rather than the stack at the moment the error happened. 

In redux-saga there is a different between the 2 moments: When an error happens the middleware bubbles the error up the call/fork chain so it can be caught by parent sagas. The propagation stops at the top level parent (root saga or a spawned saga) and at this moment the error is printed on the console.

**Comment by brabeji** [comment] 2016-05-10 10:45
I see, that's right! 

I've tried to replace `result.message` in previous code with `result.stack` and got:
![screen shot 2016-05-10 at 12 44 25 pm](https://cloud.githubusercontent.com/assets/2237954/15144000/137eee60-16ad-11e6-97cc-9cddf91e8914.png)

which is fine for me. Is that a good fix for this?

**Comment by yelouafi** [comment] 2016-05-10 11:23
>which is fine for me. Is that a good fix for this?

I think so

**Closed** 2016-05-12 10:11 UTC
Labels: bug

**Comment by yarcub** [comment] 2016-06-02 16:32
>  In the fiddle, the error is thrown while the Saga is executing a put Effect. Seems the dispatching is causing react-redux's Connect to re-render the React Component. the Error is thrown from the Saga (because it was thrown in the same stack frame of yield put)

Like mentioned on #250, i'm also trying to send all uncaught exceptions to a monitoring system. The problem is when it happens on the same frame as a `put` effect. It would simply be logged by `redux-saga` and not reach the `window.onerror` handler. 

@yelouafi, is there an option to disable this behavior and rethrow the exception? Does it makes sense?

**Comment by yelouafi** [comment] 2016-06-08 11:09
@yarcub 

If what you need is crash reporting, you can attach an error handler to the root saga

```
sagaMiddleware.run(rootSaga).catch(...)
```

**Comment by yarcub** [comment] 2016-06-14 10:48
@yelouafi, is that the correct API? 

`sagaMiddleware.run(...).catch is not a function`

**Comment by yelouafi** [comment] 2016-06-14 14:35
@yarcub should be

```js
sagaMiddleware.run(...).done.catch(...)
```

b/c `run` returns a [Task](http://yelouafi.github.io/redux-saga/docs/api/index.html#task) object not a promise
