### ISSUE TITLE
Weird error handling

### ISSUE THREAD

**Issue by burakcan** [yelouafi/redux-saga#381] opened 2016-06-11 13:28 UTC
Hello and thank you for this great library. 
I'm doing my error handling with try/catch like this (as in the docs): 
```
function *checkAuth() {
  try {
    const me = yield call(ensureAuth);
    yield put(
      createAuthSuccess(me)
    );
  } catch (e) {
    yield put(
      createAuthError(e)
    );
    window.location.href = `${oldApp}users/signin.php`;
  }
}
```
But if something wrong happens - say in the render that occurs after handling the `authSuccess` action- it just puts the `authError` action. I think this behavior is expected since that error is happening in this stack but it's really painful to debug; especially in deep function chains. Also i need to manually log actions to know if something wrong happened. Are there any recommendations to solve this problem or am i doing it completely wrong?

**Comment by yelouafi** [comment] 2016-06-13 12:21
the issue is that in JS  `catch` will catch all errors. For ex. in your example above the catch will trap both errors from the api call as well as any bug raised inside the stack frame of `put`.

So you may either test errors inside the catch to filter out 'business errors' from program bugs. Or better do not use try/catch to handle your business errors and instead use explicit return values (e.g. the return value of call(ensureAuth) can be an object with response/error props)

**Comment by coderitual** [comment] 2016-06-18 21:40
What about adding something like that next after saga middleware (not my idea and seems to be working). Ofc only for dev.
`const sagaFailMiddleware = ({ dispatch }) => next => action => {
   try {
      next(action);
   } catch (e) {
      setTimeout(() => {
         throw e;
      });
   }
};`

**Comment by burakcan** [comment] 2016-06-18 21:58
aha great idea @coderitual thank you 👍

**Comment by coderitual** [comment] 2016-06-18 22:06
@yelouafi what do you think about adding it to the sagas core? Is there a better way to handle such cases?

**Comment by yelouafi** [comment] 2016-06-21 11:39
If I understand correctly the issue addressed by the snippet above is the deep stack traces by logging the error in a fresh stack (timeout).

If that so, I don't think this has to be implemented in the core. Esp. because this would confuse users about when the errors happened (e.g. think an error with a small stack trace)

**Comment by coderitual** [comment] 2016-06-21 19:48
Right. We just use it during development as errors occured in react components are shown as those generated by the put effect and they are really hard to read atm. It also confuses people tbh but yeah, perhabs there is a better solution.

**Closed** 2016-06-24 11:29 UTC
Labels: question
